apiVersion: v1
kind: Pod
metadata:
  labels:
    run: demo-api
  name: demo-api
  selfLink: /api/v1/namespaces/default/pods/demo-api
spec:
  containers:
  - image: lukebond/demo-api:demo-gods
    imagePullPolicy: Always
    name: demo-api
    ports:
    - containerPort: 9000
      protocol: TCP
  restartPolicy: Always
  securityContext: {}
